public enum NormalMatchModes {
    NONE,
    MATCH_START,
    MATCH_WAIT,
    MATCH_ANIMATION_START,
    MATCH_ANIMATION_WORKING,
    MATCH_ANIMATION_FINISH,
    MATCH_STOP,
    MATCH_END,
    FINISH_ALL,
    OTHERS_START,
    ALL_END
}
